num1=input("Hello please type your first number of your choice. >")
num1=float(num1)
print(num1)
num2=input("Hello please type your second number of your choice. >")
num2=float(num2)
print(num2)
num3=input("Hello please type your third number of your choice. >")
num3=float(num3)
print(num3)
print ("The numbers you have chosen are: ", num1 , " ," ,num2  , " ," ,num3)
